baseURL = "http://khairulanuar.io.s3-website-ap-northeast-1.amazonaws.com"
languageCode = "en-us"
title = "Khairul Anuar"
theme = "beautifulhugo"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Never Ending "
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true

[Author]
  name = "Khairul Anuar Ariff"
  website = "yourwebsite.com"
  email = "krollquink@gmail.com"
  facebook = "username"
  github = "username"
  linkedin = "username"
  stackoverflow = "users/XXXXXXX/username"

[menu]

[[menu.main]]
name = "ABOUT ME"
url = "page/aboutme/"
weight = 1

  [[menu.main]]
    name = "BLOG"
    url = "blog/"
    weight = 2

  [[menu.main]]
    name = "TUTORIAL"
    url = "tutorial/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3





